

configurePara = struct(...
'inDataDir',  './datas/',...
'resultDir',  './results/',...    
...
...
...
'RR',         struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                     'lambdas',    [1]...
                    ),...
'STIL',       struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'lambdas'   ,[1],...
                   'mus'       ,[1]...              
                    ),...
'MTL_L',      struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'lambdas'  ,[1]... 
                    ),...
'MTIL_L_S', struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'tunedParas', struct(...
                                'lambdas'  ,   [1],...
                                 'mus' ,   [1]... %[0,1e-3,1e-2,1e-1,1,10,1e+2,1e+3]
                                 )...
                    ),...
'MTIL_L_Lc', struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'tunedParas', struct(...
                                'lambdas'  ,  [100],...
                                 'mus' ,   [5]...  %[1:5]*1e+5
                                 )...
                    ),...
'MTIL_L_Ln', struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'tunedParas', struct(...
                                        'lambdaW'  ,  [1 ],... %1,10,1e+2,1e+3,
                                        'lambdaB' ,   [1 ],... % 1,10,1e+2,1e+3,
                                        'lambdaq' ,   [1 ],... % 1,10,1e+2,1e+3,
                                        'rank'    ,  [3]... % 3
                                        )...
                   ),...
'MTIL_S_S', struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'tunedParas', struct(...
                                'lambdas'  ,   [1],...
                                 'mus' ,   [1]... 
                                 )...
                    ),...
'MTIL_S_Lc', struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'tunedParas', struct(...
                                'lambdas'  ,   [1],...
                                 'mus' ,   [1]... 
                                 )...
                    ),...
'MTIL_S_Ln', struct(...
                    'inDataDir',  '../../AllData/mtil_TKDE/datas/',...
                    'resultDir',  '../../AllData/mtil_TKDE/results/',...    
                   'tunedParas', struct(...
                                        'lambdaW'  ,  [1],... %1,10,1e+2,1e+3,
                                        'lambdaB' ,   [1],... % 1,10,1e+2,1e+3,
                                        'lambdaq' ,   [1],... % 1,10,1e+2,1e+3,
                                        'rank'    ,  [3]... % 3
                                        )...
                   )...
);
